### ISSUE TITLE
How to render dynamic route on the server

### ISSUE THREAD

**Issue by SatioO** [Dattaya/isomorphic-redux-plus#2]
How would you render a dynamic route on a TodosView.js component? (example localhost:3000/todos/1 where 1 is the id of the todo item)

In Todos component, you used:
@fetchData((state, dispatch) => dispatch(todoActions.loadTodos()))

So, In TodosView, how would you get the parameter ( 1 in this case ), and then pass it to the getTodo(id) action so that it can be rendered on the server?

**Comment by Dattaya** [comment]
@SatioO, by closing this issue does that mean that you figured it out yourself or you still need an answer?
